# Generated by Django 4.1.3 on 2022-12-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanda', '0003_domains_alter_diagnoses_id_diagnoses_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
