# Generated by Django 4.1.3 on 2022-12-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanda', '0005_classes_rename_title_domains_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnoses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
